# Fly.io 部署配置
# 文档: https://fly.io/docs/reference/configuration/

app = "ffmpeg-video-converter"
primary_region = "iad"  # 弗吉尼亚州

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8000
  force_https = true

  [[http_service.checks]]
    interval = 10000
    timeout = 2000
    method = "GET"
    path = "/health"

  [[http_service.checks]]
    interval = 10000
    timeout = 5000
    method = "GET"
    path = "/"

# 资源分配
[vm]
  memory = "512mb"
  cpu_kind = "shared"
  cpu_count = 1

# 部署策略
[deploy]
  strategy = "rolling"

# 健康检查
[[services.checks]]
  grace_period = "5s"
  interval = "15s"
  method = "GET"
  path = "/health"
  timeout = "2s"
  type = "http"